version: "3.8"

services:
  cloud-concierge:
    build: ./main/
    working_dir: /main/
    environment:
      # cloud-concierge specific env vars
      - "CLOUDCONCIERGE_APIPATH=$CLOUDCONCIERGE_APIPATH"
      - "CLOUDCONCIERGE_DIVISION=$CLOUDCONCIERGE_DIVISION"
      - "CLOUDCONCIERGE_JOBID=$CLOUDCONCIERGE_JOBID"
      - "CLOUDCONCIERGE_ORGTOKEN=$CLOUDCONCIERGE_ORGTOKEN"
      - "CLOUDCONCIERGE_NLPENDPOINT=$CLOUDCONCIERGE_NLPENDPOINT"
      - "CLOUDCONCIERGE_LOG_LEVEL=$CLOUDCONCIERGE_LOG_LEVEL"
      # Cloud scan specific env vars
      - "CLOUDCONCIERGE_PROVIDER=$CLOUDCONCIERGE_PROVIDER"
      - "CLOUDCONCIERGE_STATEBACKEND=$CLOUDCONCIERGE_STATEBACKEND"
      - "CLOUDCONCIERGE_CLOUDREGIONS=$CLOUDCONCIERGE_CLOUDREGIONS"
      - "CLOUDCONCIERGE_TERRAFORMCLOUDORGANIZATION=$CLOUDCONCIERGE_TERRAFORMCLOUDORGANIZATION"
      - "CLOUDCONCIERGE_TERRAFORMCLOUDTOKEN=$CLOUDCONCIERGE_TERRAFORMCLOUDTOKEN"
      - "CLOUDCONCIERGE_TERRAFORMVERSION=$CLOUDCONCIERGE_TERRAFORMVERSION"
      - "CLOUDCONCIERGE_RESOURCESWHITELIST=$CLOUDCONCIERGE_RESOURCESWHITELIST"
      - "CLOUDCONCIERGE_WORKSPACEDIRECTORIES=$CLOUDCONCIERGE_WORKSPACEDIRECTORIES"
      # Version control system specific env vars
      - "CLOUDCONCIERGE_VCSREPO=$CLOUDCONCIERGE_VCSREPO"
      - "CLOUDCONCIERGE_VCSTOKEN=$CLOUDCONCIERGE_VCSTOKEN"
      - "CLOUDCONCIERGE_VCSUSER=$CLOUDCONCIERGE_VCSUSER"
      - "CLOUDCONCIERGE_PULLREVIEWERS=$CLOUDCONCIERGE_PULLREVIEWERS"
    networks:
      - network
    volumes:
      - main:/main
      - ~/.aws:/main/credentials/aws:ro
      # - ~/.config/gcloud:/main/credentials/gcp:ro  # GCP credentials after authenticating with gcloud on Linux/MacOS
      # When running locally on Windows, the path to the gcloud credentials is different
      - ~/AppData/Roaming/gcloud:/main/credentials/gcp:ro
      - ~/.azure:/main/credentials/azurerm:ro


networks:
  network:
    name: cloud-concierge
    driver: bridge

volumes:
  main:
    name: main
    driver: local
