version: "3.8"

services:
  cloud-concierge:
    build: ./main/
    working_dir: /main/
    environment:
      # cloud-concierge specific env vars
      - "CLOUDCONCIERGE_APIPATH=$CLOUDCONCIERGE_APIPath"
      - "CLOUDCONCIERGE_DIVISION=$CLOUDCONCIERGE_Division"
      - "CLOUDCONCIERGE_JOBID=$CLOUDCONCIERGE_JobID"
      - "CLOUDCONCIERGE_ORGTOKEN=$CLOUDCONCIERGE_OrgToken"
      # Cloud scan specific env vars
      - "CLOUDCONCIERGE_PROVIDER=$CLOUDCONCIERGE_Provider"
      - "CLOUDCONCIERGE_STATEBACKEND=$CLOUDCONCIERGE_StateBackend"
      - "CLOUDCONCIERGE_CLOUDREGIONS=$CLOUDCONCIERGE_CloudRegions"
      - "CLOUDCONCIERGE_TERRAFORMCLOUDORGANIZATION=$CLOUDCONCIERGE_TerraformCloudOrganization"
      - "CLOUDCONCIERGE_TERRAFORMCLOUDTOKEN=$CLOUDCONCIERGE_TerraformCloudToken"
      - "CLOUDCONCIERGE_TERRAFORMVERSION=$CLOUDCONCIERGE_TerraformVersion"
      - "CLOUDCONCIERGE_RESOURCESWHITELIST=$CLOUDCONCIERGE_ResourcesWhiteList"
      - "CLOUDCONCIERGE_WORKSPACEDIRECTORIES=$CLOUDCONCIERGE_WorkspaceDirectories"
      # Version control system specific env vars
      - "CLOUDCONCIERGE_VCSREPO=$CLOUDCONCIERGE_VCSRepo"
      - "CLOUDCONCIERGE_VCSTOKEN=$CLOUDCONCIERGE_VCSToken"
      - "CLOUDCONCIERGE_VCSUSER=$CLOUDCONCIERGE_VCSUser"
      - "CLOUDCONCIERGE_PULLREVIEWERS=$CLOUDCONCIERGE_PullReviewers"
      # Cost estimation env vars
      - "CLOUDCONCIERGE_INFRACOSTAPITOKEN=$CLOUDCONCIERGE_InfracostAPIToken"
    networks:
      - network
    volumes:
      - main:/main
      - ~/.aws:/main/credentials/aws:ro
      # - ~/.config/gcloud:/main/credentials/gcp:ro
      # When running locally on Windows, the path to the gcloud credentials is different
      - ~/AppData/Roaming/gcloud:/main/credentials/gcp:ro


networks:
  network:
    name: cloud-concierge
    driver: bridge

volumes:
  main:
    name: main
    driver: local
